// Canonical list of every Legal Center document. Order here defines display
// order in both the admin editor and the public Legal Center. Adding a new
// policy in future only requires appending an entry here and publishing its
// content through the existing admin Legal Documents editor — no other code
// change is needed for it to appear in the public Legal Center.
export const LEGAL_DOCS = [
  { docType: 'terms_of_service', title: 'Terms of Service', category: 'Platform-Wide' },
  { docType: 'privacy_policy', title: 'Privacy Policy', category: 'Platform-Wide' },
  { docType: 'cookie_policy', title: 'Cookie Policy', category: 'Platform-Wide' },
  { docType: 'marketplace_rules', title: 'Marketplace Rules', category: 'Platform-Wide' },
  { docType: 'community_guidelines', title: 'Community Guidelines', category: 'Platform-Wide' },
  { docType: 'accessibility_policy', title: 'Accessibility Policy', category: 'Platform-Wide' },
  { docType: 'buyer_agreement', title: 'Buyer Agreement', category: 'Buyer' },
  { docType: 'refund_policy', title: 'Refund Policy', category: 'Buyer' },
  { docType: 'return_policy', title: 'Return Policy', category: 'Buyer' },
  { docType: 'cancellation_policy', title: 'Cancellation Policy', category: 'Buyer' },
  { docType: 'chargeback_policy', title: 'Chargeback Policy', category: 'Buyer' },
  { docType: 'seller_agreement', title: 'Seller Agreement', category: 'Seller' },
  { docType: 'product_listing_policy', title: 'Product Listing Policy', category: 'Seller' },
  { docType: 'prohibited_products_policy', title: 'Prohibited Products Policy', category: 'Seller' },
  { docType: 'restricted_products_policy', title: 'Restricted Products Policy', category: 'Seller' },
  { docType: 'vendor_subscription_policy', title: 'Vendor Subscription Policy', category: 'Seller' },
  { docType: 'commission_policy', title: 'Commission Policy', category: 'Seller' },
  { docType: 'marketplace_fees_policy', title: 'Marketplace Fees Policy', category: 'Seller' },
  { docType: 'delivery_partner_agreement', title: 'Delivery Partner Agreement', category: 'Delivery' },
  { docType: 'shipping_policy', title: 'Shipping Policy', category: 'Delivery' },
  { docType: 'delivery_policy', title: 'Delivery Policy', category: 'Delivery' },
  { docType: 'administrator_agreement', title: 'Administrator Agreement', category: 'Admin & Staff' },
  { docType: 'staff_agreement', title: 'Staff Agreement', category: 'Admin & Staff' },
  { docType: 'kyc_verification_policy', title: 'KYC Verification Policy', category: 'Trust & Safety' },
  { docType: 'identity_verification_policy', title: 'Identity Verification Policy', category: 'Trust & Safety' },
  { docType: 'aml_policy', title: 'AML (Anti-Money Laundering) Policy', category: 'Trust & Safety' },
  { docType: 'fraud_prevention_policy', title: 'Fraud Prevention Policy', category: 'Trust & Safety' },
  { docType: 'security_policy', title: 'Security Policy', category: 'Trust & Safety' },
  { docType: 'cybersecurity_policy', title: 'Cybersecurity Policy', category: 'Trust & Safety' },
  { docType: 'data_protection_policy', title: 'Data Protection Policy', category: 'Trust & Safety' },
  { docType: 'data_retention_policy', title: 'Data Retention Policy', category: 'Trust & Safety' },
  { docType: 'payment_policy', title: 'Payment Policy', category: 'Payments & Finance' },
  { docType: 'escrow_policy', title: 'Escrow Policy', category: 'Payments & Finance' },
  { docType: 'wallet_policy', title: 'Wallet Policy', category: 'Payments & Finance' },
  { docType: 'tax_policy', title: 'Tax Policy', category: 'Payments & Finance' },
  { docType: 'promotional_campaign_policy', title: 'Promotional Campaign Policy', category: 'Marketing' },
  { docType: 'advertisement_policy', title: 'Advertisement Policy', category: 'Marketing' },
  { docType: 'intellectual_property_policy', title: 'Intellectual Property Policy', category: 'Intellectual Property' },
  { docType: 'trademark_policy', title: 'Trademark Policy', category: 'Intellectual Property' },
  { docType: 'copyright_policy', title: 'Copyright Policy', category: 'Intellectual Property' },
  { docType: 'dmca_copyright_complaint_procedure', title: 'DMCA-style Copyright Complaint Procedure', category: 'Intellectual Property' },
  { docType: 'ai_usage_policy', title: 'AI Usage Policy', category: 'Technology' },
  { docType: 'ai_generated_content_policy', title: 'AI Generated Content Policy', category: 'Technology' },
  { docType: 'api_usage_policy', title: 'API Usage Policy', category: 'Technology' },
  { docType: 'third_party_integration_policy', title: 'Third-party Integration Policy', category: 'Technology' },
  { docType: 'account_suspension_policy', title: 'Account Suspension Policy', category: 'Account & Disputes' },
  { docType: 'account_termination_policy', title: 'Account Termination Policy', category: 'Account & Disputes' },
  { docType: 'user_appeals_policy', title: 'User Appeals Policy', category: 'Account & Disputes' },
  { docType: 'dispute_resolution_policy', title: 'Dispute Resolution Policy', category: 'Account & Disputes' },
  { docType: 'arbitration_policy', title: 'Arbitration Policy', category: 'Account & Disputes' },
  { docType: 'partnership_terms', title: 'Partnership Terms', category: 'Partners' },
];

export const DOC_TYPES = LEGAL_DOCS.map((d) => d.docType);
