-- JEDIDA Marketplace — Phase 46 schema
-- Digital Receipts & Invoice System.
--
-- Not a separate accounting platform — every row here hangs off the
-- existing orders/payments/shops/users/wallets/agriculture/b2b tables.
-- One generic `documents` header covers every trusted document type
-- (order confirmation, receipt, every invoice flavor, delivery receipt,
-- refund receipt, payment confirmation, business statement); `invoices`
-- and `document_line_items` extend it for the invoice/line-item cases.

CREATE TYPE document_type AS ENUM (
  'order_confirmation','digital_receipt','sales_invoice','purchase_invoice',
  'wholesale_invoice','proforma_invoice','purchase_order','delivery_receipt',
  'refund_receipt','payment_confirmation','business_statement','agriculture_bulk_invoice'
);

CREATE TYPE document_status AS ENUM (
  'draft','issued','sent','viewed','paid','partially_paid','overdue','cancelled','void'
);

CREATE TYPE invoice_category AS ENUM (
  'retail','wholesale','supplier','manufacturer','agriculture_bulk','proforma','purchase_order'
);

-- Sequence-backed human-readable numbering, one counter per document
-- type per year (e.g. JD-RCT-2026-000123).
CREATE TABLE IF NOT EXISTS document_number_sequences (
  seq_key      VARCHAR(40) PRIMARY KEY,
  last_value   BIGINT NOT NULL DEFAULT 0
);

-- ===== CORE DOCUMENT HEADER — every generated document gets exactly one row =====
CREATE TABLE IF NOT EXISTS documents (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  document_number     VARCHAR(60) UNIQUE NOT NULL,
  document_type       document_type NOT NULL,
  status              document_status NOT NULL DEFAULT 'issued',

  order_id            UUID REFERENCES orders(id) ON DELETE SET NULL,
  checkout_group_id   UUID,
  quote_request_id    UUID REFERENCES quote_requests(id) ON DELETE SET NULL,
  supply_contract_id  UUID REFERENCES supply_contracts(id) ON DELETE SET NULL,
  shop_id             UUID REFERENCES shops(id) ON DELETE SET NULL,

  issuer_id           UUID REFERENCES users(id) ON DELETE SET NULL,   -- business/seller/supplier side
  recipient_id        UUID REFERENCES users(id) ON DELETE SET NULL,   -- buyer/counterparty side

  -- Snapshots so a document still reads correctly even if the shop is
  -- renamed or the user's profile changes after the fact — a receipt is
  -- a historical record, not a live view.
  issuer_snapshot     JSONB NOT NULL DEFAULT '{}',
  recipient_snapshot  JSONB NOT NULL DEFAULT '{}',

  currency             VARCHAR(10) NOT NULL DEFAULT 'USD',
  subtotal_amount      NUMERIC(14,2) NOT NULL DEFAULT 0,
  discount_amount       NUMERIC(14,2) NOT NULL DEFAULT 0,
  tax_amount            NUMERIC(14,2) NOT NULL DEFAULT 0,
  delivery_fee_amount   NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_amount          NUMERIC(14,2) NOT NULL DEFAULT 0,

  payment_method        VARCHAR(30),
  payment_status         VARCHAR(30),
  payment_terms           TEXT,
  due_date                 DATE,

  notes                     TEXT,
  signature_url             TEXT,

  -- Security / verification (QR + code shown as "Verified Jedida Transaction")
  verification_code         VARCHAR(40) UNIQUE NOT NULL,
  qr_data_url                 TEXT,
  pdf_url                       TEXT,

  is_manual                     BOOLEAN NOT NULL DEFAULT FALSE,  -- false = auto-generated by the platform
  duplicated_from_id            UUID REFERENCES documents(id) ON DELETE SET NULL,
  created_by                     UUID REFERENCES users(id) ON DELETE SET NULL,
  metadata                        JSONB NOT NULL DEFAULT '{}',

  created_at                       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_documents_order ON documents(order_id);
CREATE INDEX idx_documents_checkout_group ON documents(checkout_group_id);
CREATE INDEX idx_documents_issuer ON documents(issuer_id, document_type);
CREATE INDEX idx_documents_recipient ON documents(recipient_id, document_type);
CREATE INDEX idx_documents_shop ON documents(shop_id, document_type);
CREATE INDEX idx_documents_type_status ON documents(document_type, status);
CREATE UNIQUE INDEX idx_documents_verification ON documents(verification_code);
CREATE TRIGGER trg_documents_updated_at BEFORE UPDATE ON documents FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ===== INVOICE EXTENSION (retail / wholesale / supplier / manufacturer / agri bulk / proforma / PO) =====
CREATE TABLE IF NOT EXISTS invoices (
  id                   UUID PRIMARY KEY REFERENCES documents(id) ON DELETE CASCADE,
  invoice_category     invoice_category NOT NULL DEFAULT 'retail',
  buyer_business_name  VARCHAR(255)
);

-- Line items — shared by invoices and multi-item receipts.
CREATE TABLE IF NOT EXISTS document_line_items (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id    UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  product_id     UUID REFERENCES products(id) ON DELETE SET NULL,
  description    TEXT NOT NULL,
  quantity       NUMERIC(12,2) NOT NULL DEFAULT 1,
  unit           VARCHAR(30),
  unit_price     NUMERIC(14,2) NOT NULL DEFAULT 0,
  line_total     NUMERIC(14,2) NOT NULL DEFAULT 0,
  sort_order     INTEGER NOT NULL DEFAULT 0,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_doc_line_items_document ON document_line_items(document_id);

-- ===== VERIFICATION LOG — every QR scan / manual code lookup (fraud protection) =====
CREATE TABLE IF NOT EXISTS document_verification_scans (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id        UUID REFERENCES documents(id) ON DELETE CASCADE,
  verification_code  VARCHAR(40) NOT NULL,
  result              VARCHAR(20) NOT NULL,  -- 'verified' | 'not_found' | 'void'
  scanned_by           UUID REFERENCES users(id) ON DELETE SET NULL,
  ip_address             VARCHAR(64),
  user_agent               TEXT,
  created_at                 TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_doc_verif_scans_doc ON document_verification_scans(document_id);
CREATE INDEX idx_doc_verif_scans_code ON document_verification_scans(verification_code);

-- ===== ADMIN DISPUTES / FRAUD FLAGS ON A DOCUMENT =====
CREATE TABLE IF NOT EXISTS document_disputes (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id    UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  raised_by       UUID REFERENCES users(id) ON DELETE SET NULL,
  reason           TEXT NOT NULL,
  status             VARCHAR(20) NOT NULL DEFAULT 'open', -- open | reviewing | resolved | dismissed
  admin_notes         TEXT,
  resolved_by           UUID REFERENCES users(id) ON DELETE SET NULL,
  resolved_at             TIMESTAMPTZ,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_doc_disputes_doc ON document_disputes(document_id);
CREATE INDEX idx_doc_disputes_status ON document_disputes(status);

-- ===== BUSINESS STATEMENTS (periodic seller/business summary document) =====
CREATE TABLE IF NOT EXISTS business_statements (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id    UUID REFERENCES documents(id) ON DELETE SET NULL,
  business_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  shop_id        UUID REFERENCES shops(id) ON DELETE SET NULL,
  period_start   DATE NOT NULL,
  period_end     DATE NOT NULL,
  total_orders   INTEGER NOT NULL DEFAULT 0,
  total_sales    NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_fees     NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_refunds  NUMERIC(14,2) NOT NULL DEFAULT 0,
  net_earnings   NUMERIC(14,2) NOT NULL DEFAULT 0,
  generated_by   UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_biz_statements_business ON business_statements(business_id);

-- Reuses the existing notifications infrastructure (schema_phase2), same
-- pattern as phase41/phase45 before it.
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'invoice_received';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'invoice_paid';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'document_disputed';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'document_verified_by_admin';
