-- Phase 39: Jedida AI Assistant layer + AI-to-human escalation for ChatV2.
-- Builds on phase 8 (chat_conversations/chat_messages) and phase 35
-- (contact-sharing moderation) — does not replace either.

-- Per-conversation AI switch and escalation state. A conversation starts
-- with the AI assistant active; once escalated, the AI stops auto-replying
-- (processIncomingMessage short-circuits) until an admin resolves it.
ALTER TABLE chat_conversations ADD COLUMN IF NOT EXISTS ai_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE chat_conversations ADD COLUMN IF NOT EXISTS escalated BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE chat_conversations ADD COLUMN IF NOT EXISTS escalation_area VARCHAR(30);
ALTER TABLE chat_conversations ADD COLUMN IF NOT EXISTS escalated_at TIMESTAMPTZ;
ALTER TABLE chat_conversations ADD COLUMN IF NOT EXISTS assigned_admin_id UUID REFERENCES users(id);

-- Marks a message as generated by the Jedida AI Assistant (as opposed to a
-- human admin's is_official message, or a regular buyer/seller message).
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS is_ai BOOLEAN NOT NULL DEFAULT FALSE;

-- One row per escalation event, so the admin escalations queue and any
-- future "average time to human handoff" reporting has a durable log even
-- after a conversation is resolved and could be escalated again later.
CREATE TABLE IF NOT EXISTS chat_ai_escalations (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id   UUID NOT NULL REFERENCES chat_conversations(id) ON DELETE CASCADE,
  user_id           UUID NOT NULL REFERENCES users(id),
  area              VARCHAR(30) NOT NULL, -- 'customer_support' | 'business' | 'delivery' | 'security'
  reason            TEXT,
  trigger_excerpt   TEXT,
  status            VARCHAR(20) NOT NULL DEFAULT 'open', -- 'open' | 'resolved'
  resolved_by       UUID REFERENCES users(id),
  resolved_at       TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ai_escalations_status ON chat_ai_escalations(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_escalations_conversation ON chat_ai_escalations(conversation_id);

-- The Jedida AI Assistant's system account. Its id is fixed so backend code
-- can reference it as a constant (see chat/aiAssistant.js) without a lookup
-- query on every message. It has no usable password (random hash, never
-- issued to any login flow) and primary_role 'admin' so it satisfies the
-- existing chat_conversations/chat_messages participant + is_official
-- checks harmlessly; the UI distinguishes it from human admins via is_ai.
INSERT INTO users (
  id, email, password_hash, full_name, phone_number, phone_verified,
  primary_role, is_admin, status, kyc_status
) VALUES (
  '00000000-0000-0000-0000-000000000001',
  'ai-assistant@system.jedida.internal',
  'not-a-real-hash-this-account-cannot-log-in',
  'Jedida AI Assistant',
  '+000000000',
  TRUE,
  'admin',
  TRUE,
  'active',
  'approved'
) ON CONFLICT (id) DO NOTHING;
