-- ============================================================
-- schema_phase23_audit_fixes.sql
-- Generated by the production-stability database audit.
-- Purely additive: ADD COLUMN / ADD VALUE only. Nothing is dropped,
-- renamed, or backfilled destructively. Safe to run against a live
-- database with existing data.
-- ============================================================

-- ------------------------------------------------------------
-- FIX 1 (CRITICAL): role_upgrades.status is typed as the
-- `upgrade_status` enum, which only defines:
--     none, pending_payment, pending_approval, approved, rejected
-- but upgradeController.js (requestUpgrade / submitPayment / submitKyc /
-- submitOneTimeUpgrade / admin review flows) reads and writes these
-- additional values:
--     payment_submitted, payment_verified, payment_rejected,
--     kyc_pending, kyc_verified, kyc_rejected
-- Every write of these values currently throws:
--   error: invalid input value for enum upgrade_status: "payment_submitted"
-- This is almost certainly the source of the "column/value does not
-- exist" errors seen on seller/delivery upgrade endpoints.
-- ADD VALUE cannot run inside the same transaction that uses the new
-- value, but is safe as a standalone statement (Postgres 12+).
-- ------------------------------------------------------------
ALTER TYPE upgrade_status ADD VALUE IF NOT EXISTS 'payment_submitted';
ALTER TYPE upgrade_status ADD VALUE IF NOT EXISTS 'payment_verified';
ALTER TYPE upgrade_status ADD VALUE IF NOT EXISTS 'payment_rejected';
ALTER TYPE upgrade_status ADD VALUE IF NOT EXISTS 'kyc_pending';
ALTER TYPE upgrade_status ADD VALUE IF NOT EXISTS 'kyc_verified';
ALTER TYPE upgrade_status ADD VALUE IF NOT EXISTS 'kyc_rejected';

-- ------------------------------------------------------------
-- FIX 2 (MEDIUM): LegalAndSystemService.js selects `updated_at` from
-- legal_documents (public Legal Center index), but that column was
-- never added to the table — only created_at/updated_by exist.
-- Adds it with a safe default so existing rows are unaffected; new
-- document versions (inserted, never updated, per the existing
-- versioning design) will get the correct timestamp automatically.
-- ------------------------------------------------------------
ALTER TABLE legal_documents ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- ------------------------------------------------------------
-- FIX 3 (defensive / low risk): a small number of ALTER TABLE
-- statements in earlier phase files (chat_messages.pinned,
-- deliveries.current_lat/current_lng/location_updated_at,
-- platform_settings.* columns, orders.checkout_group_id/cancelled_at/
-- cancellation_reason, payments.payer_phone/transaction_reference/
-- proof_image, ads.* columns) reference tables that are created in a
-- *later*-numbered phase file. Under the old lexical sort order those
-- ALTERs ran before the CREATE TABLE that defines their target and
-- would have failed on a fresh database. Restated here as
-- IF NOT EXISTS/IF EXISTS-guarded statements so that, regardless of
-- history, a `node migrate.js` run against any environment converges
-- to the same end state. All of these are safe no-ops if already applied.
-- ------------------------------------------------------------
ALTER TABLE IF EXISTS chat_messages ADD COLUMN IF NOT EXISTS pinned BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE IF EXISTS deliveries ADD COLUMN IF NOT EXISTS current_lat NUMERIC(9,6);
ALTER TABLE IF EXISTS deliveries ADD COLUMN IF NOT EXISTS current_lng NUMERIC(9,6);
ALTER TABLE IF EXISTS deliveries ADD COLUMN IF NOT EXISTS location_updated_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS orders ADD COLUMN IF NOT EXISTS checkout_group_id UUID;
ALTER TABLE IF EXISTS orders ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS orders ADD COLUMN IF NOT EXISTS cancellation_reason TEXT;

ALTER TABLE IF EXISTS payments ADD COLUMN IF NOT EXISTS payer_phone VARCHAR(30);
ALTER TABLE IF EXISTS payments ADD COLUMN IF NOT EXISTS transaction_reference VARCHAR(255);
ALTER TABLE IF EXISTS payments ADD COLUMN IF NOT EXISTS proof_image TEXT;

CREATE INDEX IF NOT EXISTS idx_chat_messages_pinned ON chat_messages(pinned) WHERE pinned = TRUE;
CREATE INDEX IF NOT EXISTS idx_orders_checkout_group ON orders(checkout_group_id);
